# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4acb67ac4faf33f05a286cb853a61667d7c5223a79539f7c84f6a25bc8753f66b7d3da9a8546675086be91048e13edaef43c45cc34dc5c1cd08ca306ee68a72

test:
  secret_key_base: 115b8e506772cde69bcbaa48cfc20776e966d16ea3e20d18858e1a430e47b25a128faa08205855ef3049768f07dd50f36206561c0b23dc77a9ef09557091e167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
